### PR TITLE
Ummm... I did that thing you said, I think.

### PR DESCRIPTION
**Pull request by Yubelious**
I gave the boxes a definitive height instead of a max height, and tested to make sure the font fits every currently available resolution. I didn't get why the transform was there,  so you can put that back if you need to. I leave the coloring to you.

### CODE REVIEW

**Comment by Skeletonxf** [comment]
I definitely want to merge in the fixed sizes into all the css you've got as the current styles are a little weird with no card selected. The transform was there to make the card title fixed to the top left of the column, but not part of the relative positioning within the card description div. This meant it saved vertical space for the card text.

However I think it would be best to keep things like font sizes varied and have several styles to select each tailored to different screen sizes. The absolute positioning and transform for instance is not helpful on big screens, and on very small screens will cause some text to get cut off, but on medium sized screens that are wide but not tall it saves very useful vertical space. Similarly the scrolling card image won't be saving any space on a large screen either, but helps on small screens.

I tested the file and there's a syntax error on line 41, and on my addons page Stylish says the style can affect any site, when it is supposed to just affect dueling nexus. I think that's related to the change to the `@-moz-document` at the beginning, which is still weird with it still saying dueling nexus in the code.

After fixing/removing those things I see this:

[http://i.imgur.com/QjVgKF9.png](url)

This is probably well suited to a 4k screen, as the font sizes on there would be much more readable than their defaults, but on my 1080p screen I can barely see a monster effect, and on my laptop where I made the original Style in the first place I imagine I would struggle a lot. By contrast this is what the current style looks like

[http://i.imgur.com/MUkR5kC.png](url)

Clearly this font size is too small for a larger screen, it's a bit small even on this screen, and the description box having a fixed size would improve the looks and avoid nested scroll bars which probably won't look so good on Windows as they're so much larger there. 

Because of these reasons I'm accepting the pull request, then restoring the style beforehand as a separate file and renaming both to make things a little clearer. We can then work through merging in the useful parts of each to each other and decide how many css versions will be useful.

Also we are going to have to sort out licensing, because by default everyone owns the copyright over what they write. I licensed my style under CC0/Public domain initially which meant you had no issues building off of it, but you would have to do the same for me to now copy the code from yours to merge in the fixed sized boxes into the code I wrote.

Hence I changed the license of my current style to GPL3 which you can see in the LICENSE file. The original you built off will remain public domain forever so your current style has no concerns there. If we just decide to have everything in this repository under GPL3 then there's no issues with copying from each other, but you will need to make your own decision as to how to license your code. While GPL more or less removes any issue with copying within a project, it is also incompatible with most other licenses, in that it cannot be copied into, say, a MIT licensed project (even though code from a MIT licensed project can be copied into a GPL project ¯\_(ツ)_/¯).

**Comment by Skeletonxf** [comment]
Also it's probably a good idea for both of us to start commenting on what not immediately obvious lines of code do

**Comment by Yubelious** [comment]
I was testing on Firefox. I was going to test on Opera last night, but ran out of time. We'll need to work on cross-browser support,  so it works on Firefox,  Chrome, and Opera. But I'm not gong to bother with that oriental browser until I get my own computer fixed.

**Comment by Yubelious** [comment]
Could you test resolutions on Chrome? And I'll take Opera. @Skeletonxf 

As for licensing, I suppose it's a matter of whether or not we want Dueling Nexus to one day use our code. I mean, if one day they decided "hey, we should add a chat box" and adding a chat box breaks our license, well, that's a problem I'd rather not run into.

I like Dueling Nexus, and I don't want this having legal issues. This sort of thing confuses me.

**Comment by Skeletonxf** [comment]
I'll test on Chrome. That's a good point, Dueling Nexus ideally should have an easy time using this css. GPL would cause problems as they're unlikely to want to open source all their code just to use the chatbox css for this.

I propose we license this whole repository's code under MIT https://opensource.org/licenses/MIT then. That way they'll have an easy enough time using it if they want to; we would just have to be credited somewhere, not even asked.

**Comment by Yubelious** [comment]
(Wow. I actually understood that.) I second this propsal. I would also like to express my intended role.

I merely wish to be a colaborator on the project, and not a proprietor of a seperate project being merged onto yours. However, I do intend to include many aspects of what we are doing in version 1.2 of my stylish, crediting you for... something,  I'll figure that out later.

**Pull request merged**
