### PR TITLE
Create Deck selection scroll

### PR DESCRIPTION
**Pull request by Yubelious**
Here's the scrolling deck selection I mentioned earlier.

### CODE REVIEW

**Comment by Skeletonxf** [comment]
I had thought you wanted to merge the scrolling of deck selection into the existing css but either way looks good.

**Comment by Yubelious** [comment]
Well, I'd like them made first. Then we can decide together what to do with
them.


_Sent from my Samsung SGH-I337M using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Skeletonxf** [comment]
I extracted a more minimalist style out of it to add scrolling and not change visuals and pushed it to style-small.css

I presume more elaborate styling would fit for style-large.css similar to what you have there

On that styles what are the following lines for?

```css
cursor: s-resize;
display: none;
position: absolute;
```

Oh also as I was adding scrolling to style-small I accidentally added scrolling to the in game banish/extra/grave/deck/selection things which I also imagine might be useful for some decks that do a lot of milling or searching. I thought this was what the pull request had added :laughing:  and only realized after that this is just targeting the pregame menu.

**Comment by Yubelious** [comment]
The cursor defines how the mouse appears on hover. It indicates the area is
scrollable. This is mostly to assist our Mac users.

I don't know what none indicates. It was in the code I ripped from...
something to do with the pop up. I forget specifically which.

Absolut is vodka. But it also works in conjuction with z-index. I also took
that from code in the DNx stylesheet.

Make sure the waiting popup doesn't scroll. I'll probably play with it more
on Monday. I'm taking Sunday off. 

_Sent from my Samsung SGH-I337M using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Pull request merged**
